### ISSUE TITLE
Omnibar misbehaves with URLs containing HTML anchors

### ISSUE THREAD

**Issue by Mesqalito** [Quicksaver/Omnibar-Plus#4]
Two issues, actually. They apper after clicking on anchor or simply navigating to an URL with an anchor.
1. Single clicking on a location bar does not make text cursor to appear. Clicking second time does what is expected.
2. Focusing location bar and hitting Enter makes location bar to clear its contents. Hitting Esc restores URL back.

These do not reproduce when Omnibar Plus is disabled.
Sample URL to reproduce bug:
http://en.wikipedia.org/wiki/Vertex_%28computer_graphics%29#Vertex_attributes

**Comment by Quicksaver** [comment]
I was never able to reproduce this...

**Comment by Mesqalito** [comment]
But an issue still persists. With last FF update (17) it got even worse: now blank page does not allow to navigate to url in location bar - it just ignores pressing Enter. Unfortunately, this behavior forced me to stop using Omnibar Plus addon.

For your info, I have made a report from my about:support page in FF.
Here it is:
https://gist.github.com/5bc6391c9d3fc245a759#file_ff17%20about:support

**Comment by Quicksaver** [comment]
I still cannot reproduce any of the bugs you are mentioning. I can click on the location bar and it always shows the cursor, whether the url has any anchors or not. Pressing enter always opens the address as expected, whether it is from blank pages or from any other webpages. I was going to say it could be because of an outdated Tab Mix Plus but I see that you have the latest dev version, same as me. If you could, please try the following:

1) Try the latest version of the add-on, 1.0.4, it is still awaiting review automatic updates to it aren't enabled yet, but you can find it at https://addons.mozilla.org/en-US/firefox/addon/omnibar-plus/versions/ at the top of the page.

2) If with that version the bugs still happen, try creating a new profile (instructions on how to at http://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles ), and install only Omnibar and Omnibar Plus. See if the bugs still occur. If they do then I'd ask you for instructions on how to reproduce this as detailed as possible because, like I said, everything is working fine for me, so it must be something really specific for me to miss it like this. If they don't occur, it could be a combination of Omnibar Plus with some other add-on you have enabled, so you'll have to disable and re-enable them one at a time to find out which it is.
