### ISSUE TITLE
Latest Firefox nightlies have broken Omnibar Plus again

### ISSUE THREAD

**Issue by mcl21014** [Quicksaver/Omnibar-Plus#8]
I can export some error console output if needed. Basically, Mozilla has redefined some UI elements for some reason and this has broken the ability for the UI to respond at all. If I try to open a new tab, although technically opened, this will not be shown in the tab bar at all.

**Comment by mcl21014** [comment]
This only happens on a normal startup. Restarting Firefox after enabling the addon will not trigger the bug. Here is some error console output:
Timestamp: 4/28/2013 12:45:30 PM
Error: [Exception... "'TypeError: this.browsers[i] is undefined' when calling method: [nsIDOMGlobalPropertyInitializer::init]"  nsresult: "0x8057001c (NS_ERROR_XPC_JS_THREW_JS_OBJECT)"  location: "JS frame :: resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/Users/Michael/AppData/Roaming/Mozilla/Firefox/Profiles/86kufs8m.default-1367180479710/extensions/omnibarplus@quicksaver.xpi!/bootstrap.js -> resource://omnibarplus/modules/utils/moduleAid.jsm -> resource://omnibarplus/modules/utils/overlayAid.jsm :: <TOP_LEVEL> :: line 184"  data: no]
Source File: resource://gre/modules/XPIProvider.jsm -> jar:file:///C:/Users/Michael/AppData/Roaming/Mozilla/Firefox/Profiles/86kufs8m.default-1367180479710/extensions/omnibarplus@quicksaver.xpi!/bootstrap.js -> resource://omnibarplus/modules/utils/moduleAid.jsm -> resource://omnibarplus/modules/utils/overlayAid.jsm
Line: 184

**Comment by Quicksaver** [comment]
Are you sure this is an actual change and not just a Nightly-related bug, which are fairly common and usually fixed within a couple of days? I usually only test in Aurora because of these, many times a nightly build will break something (by accident or on purpose, it doesn't matter), only to fix it in the next update or two. I say this because nowhere in my code is there a reference to "this.browsers[i]" which is weird, even though there are a few browsers[i] but those shouldn't show up with a "this." prefix in the error console as far as I know.

Either way, I'll check it out to make sure. If in the meantime, a Nightly update resolves this issue, let me know.

**Comment by mcl21014** [comment]
Sure thing. Nightly loves to break all the time. I know this. I’ll delete the bug if it goes away and stays away.

Sent from Windows Mail

**Comment by Quicksaver** [comment]
I just tested on the latest Nightly and it seems to be working fine now. And it was always working in the Auroras these past few weeks, so I'm closing this for now. Reopen if this behavior comes back.
